"""Format InfraScope results as a GitHub PR comment with collapsible sections."""
import logging
import os

from github import Github

from .cost_analysis import CostSummary
from .iam_blast_radius import RoleBlastRadius
from .policy_lint import PolicyFinding
from .security_score import SecurityScore

log = logging.getLogger(__name__)


def format_comment(
    score: SecurityScore,
    blast_results: list[RoleBlastRadius],
    policy_findings: list[PolicyFinding],
    cost: CostSummary | None,
    ai_narrative: str | None = None,
) -> str:
    """Build the full PR comment markdown."""
    parts = []

    # header with score
    icon = "🟢" if score.passed else "🔴"
    parts.append(f"## {icon} InfraScope Security Analysis--Score: {score.overall}/100 ({score.grade})")
    parts.append("")

    if score.critical_count:
        parts.append(f"> **{score.critical_count} critical finding(s)** must be resolved before merge.")
        parts.append("")

    # AI narrative summary (if available)
    if ai_narrative:
        parts.append(ai_narrative)
        parts.append("")

    # blast radius section
    if blast_results:
        parts.append("<details>")
        parts.append("<summary><strong>IAM Blast Radius Analysis</strong></summary>")
        parts.append("")
        for br in blast_results:
            parts.append(f"### `{br.role.name}`--{br.overall_severity.upper()}")
            if br.wildcard_actions:
                parts.append(f"⚠️ Wildcard actions: `{'`, `'.join(br.wildcard_actions)}`")
            parts.append("")
            parts.append("| Action | Category | Severity | Scope |")
            parts.append("|--------|----------|----------|-------|")
            for c in br.classifications[:20]:  # cap at 20 rows
                parts.append(f"| `{c.action}` | {c.category} | {c.severity} | {c.resource_scope} |")
            if len(br.classifications) > 20:
                parts.append(f"| ... | {len(br.classifications) - 20} more | | |")
            parts.append("")
        parts.append("</details>")
        parts.append("")

    # policy findings
    if policy_findings:
        parts.append("<details>")
        parts.append("<summary><strong>Policy Findings</strong></summary>")
        parts.append("")
        for f in policy_findings:
            icon = {"critical": "🔴", "high": "🟠", "medium": "🟡"}.get(f.severity, "⚪")
            parts.append(f"{icon} **{f.rule}** ({f.severity})--`{f.resource_address}`")
            parts.append(f"  {f.detail}")
            parts.append(f"  → {f.recommendation}")
            parts.append("")
        parts.append("</details>")
        parts.append("")

    # cost section
    if cost:
        parts.append("<details>")
        parts.append("<summary><strong>Cost Impact</strong></summary>")
        parts.append("")
        delta = f"+${cost.delta_monthly:.2f}" if cost.delta_monthly > 0 else f"${cost.delta_monthly:.2f}"
        parts.append(f"Estimated monthly cost: **${cost.total_monthly:.2f}** ({delta}/mo)")
        parts.append("")
        if cost.top_drivers:
            parts.append("| Resource | Type | Monthly |")
            parts.append("|----------|------|---------|")
            for item in cost.top_drivers:
                new = " 🆕" if item.is_new else ""
                parts.append(f"| {item.resource_name}{new} | {item.resource_type} | ${item.monthly_cost:.2f} |")
        parts.append("")
        parts.append("</details>")
        parts.append("")

    # score breakdown
    parts.append("<details>")
    parts.append("<summary><strong>Score Breakdown</strong></summary>")
    parts.append("")
    parts.append("| Dimension | Score | Weight |")
    parts.append("|-----------|-------|--------|")
    for b in score.breakdown:
        parts.append(f"| {b.dimension} | {b.score}/100 | {b.weight:.0%} |")
    parts.append("")
    if any(b.deductions for b in score.breakdown):
        parts.append("**Deductions:**")
        for b in score.breakdown:
            for d in b.deductions:
                parts.append(f"- [{b.dimension}] {d}")
    parts.append("")
    parts.append("</details>")
    parts.append("")

    parts.append("---")
    parts.append("*Generated by [InfraScope](https://github.com/WingedGuardian/cloudpipe)--AI-powered infrastructure analysis*")

    return "\n".join(parts)


def post_comment(body: str, repo: str, pr_number: int) -> None:
    """Post or update the InfraScope comment on a PR."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        log.warning("GITHUB_TOKEN not set, writing comment to stdout")
        print(body)
        return

    gh = Github(token)
    repo_obj = gh.get_repo(repo)
    pr = repo_obj.get_pull(pr_number)

    # update existing comment if present (avoid spam on re-runs)
    marker = "Generated by [InfraScope]"
    for comment in pr.get_issue_comments():
        if marker in (comment.body or ""):
            comment.edit(body)
            log.info("updated existing InfraScope comment")
            return

    pr.create_issue_comment(body)
    log.info("posted new InfraScope comment on PR #%d", pr_number)
